#!/usr/bin/env python3
"""
inject_footer_last_reviewed.py

Idempotently injects (or refreshes) the "Last reviewed: <date>" footer line
on every static HTML page, pulling the date from /content/site-meta.json.
The line is wrapped in an anchor pointing to /version so the reader can verify
the build provenance.

Run from the repo root:
  python3 scripts/inject_footer_last_reviewed.py

Skips:
  - api/**, node_modules/**, .git/**, dist/**
  - research/*.html  (regenerated by scripts/build_operators.py — that script
    has its own footer template; running build_operators.py picks up changes)

The match-pattern is the unique copyright span inside .footer-meta. The new
anchor sits between the copyright and the nav-links span. If a prior version
of the line already exists (any tag with class="footer-last-reviewed"), it
is replaced — that keeps the date current when site-meta.json changes.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE_META = ROOT / "content" / "site-meta.json"
SKIP_DIRS = {"api", "node_modules", ".git", "dist", ".vercel"}
SKIP_GLOBS = ("research/*.html",)  # operator pages are template-generated

COPYRIGHT_SPAN_RE = re.compile(
    r'(<span>&copy; 2025[-–—]2026 Halvren Capital\. All rights reserved\.</span>)\s*'
)
EXISTING_LINE_RE = re.compile(
    r'\s*<(?:span|a)[^>]*class="footer-last-reviewed"[^>]*>.*?</(?:span|a)>\s*',
    re.DOTALL,
)


def build_anchor(date_human: str) -> str:
    return (
        f'<a href="/version" class="footer-last-reviewed" '
        f'title="Build provenance and changelog"><strong>Last reviewed:</strong> '
        f'{date_human}</a>'
    )


def should_skip(path: Path) -> bool:
    rel = path.relative_to(ROOT)
    if any(part in SKIP_DIRS for part in rel.parts):
        return True
    rel_str = rel.as_posix()
    return any(Path(rel_str).match(g) for g in SKIP_GLOBS)


def transform(html: str, anchor: str) -> tuple[str, bool]:
    """Returns (new_html, changed)."""
    # First, strip any existing footer-last-reviewed element (idempotent refresh).
    cleaned = EXISTING_LINE_RE.sub("\n    ", html)
    # Then, inject the new anchor right after the copyright span.
    new_html, n = COPYRIGHT_SPAN_RE.subn(rf"\1\n    {anchor}\n    ", cleaned, count=1)
    if n == 0:
        # No copyright span found — page does not use the standard footer-meta.
        return html, False
    return new_html, new_html != html


def main() -> int:
    if not SITE_META.exists():
        sys.stderr.write(f"missing {SITE_META.relative_to(ROOT)}\n")
        return 1
    meta = json.loads(SITE_META.read_text(encoding="utf-8"))
    date_human = meta.get("last_full_site_review_human") or meta.get("last_full_site_review")
    if not date_human:
        sys.stderr.write("site-meta.json missing last_full_site_review_human/iso\n")
        return 1
    anchor = build_anchor(date_human)

    touched = 0
    skipped_no_footer = 0
    for path in sorted(ROOT.rglob("*.html")):
        if should_skip(path):
            continue
        original = path.read_text(encoding="utf-8")
        new_html, changed = transform(original, anchor)
        if not changed and COPYRIGHT_SPAN_RE.search(original) is None:
            skipped_no_footer += 1
            continue
        if changed:
            path.write_text(new_html, encoding="utf-8")
            touched += 1
            print(f"  updated {path.relative_to(ROOT)}")

    print(f"inject_footer_last_reviewed: touched {touched} file(s); "
          f"skipped {skipped_no_footer} without standard footer-meta.")
    print("note: research/*.html is regenerated by scripts/build_operators.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
